name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SSH and deploy
        run:  ssh root@94.103.183.26
      - name: Enter password
        run:  lZ5lS0dH1cbI